spring:
  profiles:
    active: local

# enable this to use a custom download path to mongo
#custom:
#  mongo-download-path: http://my.domain.com/mongo-dist/

---

spring:
  profiles: local

---

spring:
  profiles: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/message-db
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration