spring:
  data:
    rest:
      base-path: /api/v1
---
spring:
  profiles: database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: iamroot
  jpa:
    hibernate:
      ddl-auto: create

