# create
POST http://localhost:8080/products
Content-Type: application/json

{
  "description": "My awesome product",
  "price": 42.5
}

###

# read
GET http://localhost:8080/products

###

# update
POST http://localhost:8080/products
Content-Type: application/json

{
  "id": 1,
  "description": "Changed",
  "price": 42.5
}

###

# delete
DELETE http://localhost:8080/products/2

###

# will produce a bad request
POST http://localhost:8080/products
Content-Type: application/json

{
  "description": ""
}