# create
POST http://localhost:8080/products
Content-Type: application/json

{
  "description": "My awesome product",
  "price": 42.5
}

###

# read all
GET http://localhost:8080/products

###

# read single
GET http://localhost:8080/products/1

###

# update
PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "description": "Changed",
  "price": 42.5
}

###

# partial update
PATCH http://localhost:8080/products/1
Content-Type: application/json

{
  "price": 999.99
}

###

# delete
DELETE http://localhost:8080/products/2

###

# will produce a bad request
POST http://localhost:8080/products
Content-Type: application/json

{
  "description": ""
}