POST http://localhost:8080/products
Content-Type: application/json

{
  "description": "Changed",
  "price": 42.5
}

###

GET http://localhost:8080/products

###

DELETE http://localhost:8080/products/3
