name:                gi-gtk
version:             0.1.0.0
github:              "enolive/gi-gtk"
license:             BSD3
author:              "Christoph Welcz"
maintainer:          "christoph@welcz.de"
copyright:           "2019 Christoph Welcz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/enolive/gi-gtk#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  gi-gtk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gi-gtk

tests:
  gi-gtk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gi-gtk
