name:                tennis-game
version:             0.1.0.0
github:              "enolive/tennis-game"
license:             MIT
author:              "Christoph Welcz"
maintainer:          "christoph@welcz.de"
copyright:           "2019 Christoph Welcz"
# synopsis: A new project for TDD with Haskell.
# description: tennis-game see README.md for further details.
# category: Other

extra-source-files:
- README.md
- package.yaml
- LICENSE.md

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tennis-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tennis-game

tests:
  tennis-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tennis-game
    - hspec
    - QuickCheck
