name:                aws-lambda
version:             0.1.0
github:              "githubuser/aws-lambda"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/aws-lambda#readme>

dependencies:
  - base >= 4.7 && < 5
  - aws-lambda-haskell-runtime >= 2.0.1
  - aeson

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
      - -static
      - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
      - aws-lambda

default-extensions:
  - TemplateHaskell
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
