spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:iamroot@localhost:5432/postgres
  liquibase:
    change-log: classpath:db/changelog.xml
    # XXX: as we have no spring-data-jdbc support, we need to specify our database connection directly
    url: jdbc:postgresql://localhost:5432/postgres
    password: iamroot
    user: postgres
