---
spring:
  profiles: local
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: iamroot
  liquibase:
    # XXX: as we have no spring-data-jdbc support, we need to specify our database connection directly
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: iamroot
---
spring:
  profiles: testdb
  r2dbc:
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: